name: Terraform Manual Workflow
env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Select Environment'
        options:
        - prod-env
        - develop-env
        required: true
        default: 'develop-env'
      terraform:
        type: choice
        description: 'Select Method'
        options:
          - apply
          - destroy
        required: true
        default: 'apply'
      tenant-id:
        type: string
        description: 'Enter Tenant Id'
        required: true

jobs:

  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    environment: prod-env
    steps:
    - name: Checkout
    - uses: actions/checkout@v3
    # - uses: hashicorp/setup-terraform@v1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2 
    - name: Terraform Initialize
      run: cd infa && terraform init
    - name: Print User Selection
      # id: selection
      run: |
        echo "Env: ${{ github.event.inputs.env }}" 
        echo "Terraform Action is: ${{ github.event.inputs.terraform }}"
    - name: Print Tenant Id
      run: |
        echo "Tenant Id: ${{ github.event.inputs.tenant-id}}"
<<<<<<< HEAD
    - name: Terraform apply
      run: cd infra  && terraform ${{ github.event.inputs.terraform}} -auto-approve


=======
    - name: Checkout Code
      uses: actions/checkout@v2
>>>>>>> parent of 3459873 (commit 18)

    # - name: Configure AWS CLI
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    # - name: create sns-topic
    #   run: |
    #     aws sns create-topic --name outbox-topic-${{ github.event.inputs.tenant-id}}
    #     aws sns list-topics
  