name: Terraform Manual Workflow
env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
  workflow_dispatch:
    inputs:
      deployment:
        type: choice
        description: 'Select Environment'
        options:
        - prod-env
        - develop-env
        required: true
        default: 'develop-env'
      terraform:
        type: choice
        description: 'Select Terraform Action'
        options:
          - apply
          - destroy
        required: true
        default: 'apply'
      tenant-id:
        type: string
        description: 'Enter Tenant Id'
        required: true
#      sns-topic-arn:
#        type: string
#        description: 'Enter SNS Topic ARN'
#        required: true
jobs:

  infrastructure-setup:
    name: building the cloud infra
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.deployment}}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
      - name: Insert tenant_id in tenant.tf file
        run: | 
          
          echo 'variable  "tenant_id"  { ${{github.event.inputs.tenant-id}} } > ../infra/tenant.tf' &&  cd ../infra/ && cat tenant.tf
      - name: Print Main.tf file
        run: cd infra && cat main.tf
      - name: Run terraform init in terraform dir
        run: cd infra && terraform init
      - name: Print User Deployment Selection
        run: |
          echo "Environment: ${{github.event.inputs.deployment}}"
          echo "Tenant Id: ${{github.event.inputs.tenant-id}}"
      

      - name: Terraform ${{github.event.inputs.terraform}}
        run: cd infra && terraform ${{github.event.inputs.terraform}} -auto-approve



 



    # - name: Configure AWS CLI
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    # - name: create sns-topic
    #   run: |
    #     aws sns create-topic --name outbox-topic-${{ github.event.inputs.tenant-id}}
    #     aws sns list-topics
  