name: Terraform Manual Workflow
on:
  workflow_dispatch:
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l 
      - run: echo 'hello world'
