name: Terraform Manual Workflow
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Select Environment'
        options:
        - prod-env
        - develop-env
        required: true
      terraform:
        type: choice
        description: 'Select Method'
        options:
          - apply
          - destroy
        required: true

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2 
    - name: Create Directory
      run: |
        mkdir -p datadog \
        cd datadog && echo  'hello' EOF > a.txt \
        cat a.txt

    
