name: Terraform Manual Workflow
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Select Environment'
        options:
        - prod-env
        - develop-env
        required: true

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l 
      - run: echo 'hello world'
