name: Terraform Manual Workflow
on:
  workflow_dispatch:
    env:
      inputs:
        user_input:
          type: choice
          description: 'Select Environment' 
          options:
          - dev
          - stage
          - prod
          required: true
          defaults: dev
jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -l 
      - run: echo 'hello world'
